apiVersion: v1
kind: Secret
metadata:
  name: argoproj-ssh-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  url: git@github.com:prometheus-operator/kube-prometheus.git
  type: jsonet
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAYEA0/UWfABhYqGPmlCTHgI57fDUqZl64hpz1l+fyeCzjOSet3z6kcRl
    n9ajWWZh164KChq5NAoJjXEVsjXqcq9IwuUVqmE4NcEaLTJv40n2gYhwkvzO7O7eALBZrX
    xJbX4l/y0AekbDiu9d73TAwUkDO5XMk0N2qxG75s69+nxHe8/yPx2btvtlpZEmgmQMJkSh
    bXSZCvbLlMMU+rj0MjfXnmbBPJFZKOXXmv4LBtmO6OocdAPMOUbdem3+3PFKku/ALCGCEY
    +GsMSpR304a5tQjqapD2BFXS2qPzgSx3UClKpeWVVHM60g1t7dGwpG8gjDpMk/AkdK7tE7
    tlCrnj64IP3U1b2otKuJ6GzKjUhdRfAhFXWiDdyzP+H2o/afLb5LxYc1kAm8bYxpFPOWTg
    Y7EDs8gB4SqHwhel5FGQ11pgYW7/lOWjszisy/+jv12SpizhIPUxNStMDeJmhCgOeXNE7o
    tZl91zA2oWS/0aUeXew8yeE1LMt9YLvVAmeVko6nAAAFmMjVItLI1SLSAAAAB3NzaC1yc2
    EAAAGBANP1FnwAYWKhj5pQkx4COe3w1KmZeuIac9Zfn8ngs4zknrd8+pHEZZ/Wo1lmYdeu
    CgoauTQKCY1xFbI16nKvSMLlFaphODXBGi0yb+NJ9oGIcJL8zuzu3gCwWa18SW1+Jf8tAH
    pGw4rvXe90wMFJAzuVzJNDdqsRu+bOvfp8R3vP8j8dm7b7ZaWRJoJkDCZEoW10mQr2y5TD
    FPq49DI3155mwTyRWSjl15r+CwbZjujqHHQDzDlG3Xpt/tzxSpLvwCwhghGPhrDEqUd9OG
    ubUI6mqQ9gRV0tqj84Esd1ApSqXllVRzOtINbe3RsKRvIIw6TJPwJHSu7RO7ZQq54+uCD9
    1NW9qLSriehsyo1IXUXwIRV1og3csz/h9qP2ny2+S8WHNZAJvG2MaRTzlk4GOxA7PIAeEq
    h8IXpeRRkNdaYGFu/5Tlo7M4rMv/o79dkqYs4SD1MTUrTA3iZoQoDnlzRO6LWZfdcwNqFk
    v9GlHl3sPMnhNSzLfWC71QJnlZKOpwAAAAMBAAEAAAGBAMl/gsuJlQst6hXaqbFqjmXMgG
    9nMDII0bynlYFWs3qq0NRA5Ph0i+PjKdFQio1+r56hfxWgwSoMqoKLzQEP8A0PuYQK/mPj
    2p3DCCk8ZDMKYXLrEVCfWL+w5uANesSzmy22O3EDGtxW6Kc/CAv3/DHGHACXrxW8OzSVsH
    eTdGWY74PfAux2nFBE6CYnNIGg1xH2OZP5wNoAh04/TC79dWbp6qRIzUkbD9gR0KvHYZu9
    DCWigqCk5OKB9TtXy/xaHEzCWgo/XYK8qr5W3os8gd6xr4hhPAPVBYFMd89xvWsU+cFdoC
    by1xs/unxPiAq2JtWoc1f8ULWqnpw5yPqNobcGEs5EoDn29jzJhT3cKjkZ3QWHAtRwj3xG
    xGXaYJeng+MZWNH7Yy3GUVYEALXaIfKk2YVQjWu9idnhSbZTm2OIqLvkTF5jw1KR+0WDlV
    k3XGLX4bBOo2aTi0e90jTp/bAvmI2lTufqnS9A255aklKtLzk9KpuUt2fVKoxKtG7EiQAA
    AMADIrOYPMl2nwsPrSwnZJqCJ91o3io9GGDcQ4FWi2Wp+Pz/01lW3+jQURQ5OMssk/aQCm
    A8RB6W/WKJKlVaENCH1R/3XeFsXgxyMTi741GZKGbbr1AEv5m+zJv6shpP/B7GAb/KABgo
    vAy8tMzxazHMUrysuoqi/M/ue8A1IkyH3ANjbvtJrYWpl5PwpfPAC1/+uiNI+3we4TSKu/
    JZWXdpgJK+ickHstubkgAmz1DfzaA3W81ODT1Q6JIyAkF9vosAAADBAPODz9+Ib9GUGEtr
    nwsVxLHS7bJ8JjTv9NMAHje0A3UdJRSpyRXGA6EVajKo8xGi/cVxliCfwLfht3/tUSJDlE
    E64AuhQbSy8Q0cRkIxidsTi3bVL/9O76XD4OuiZ8VIjcD2lahPOScszWseWWFC5lOQgEbL
    RHhjntmIVN02cta2D/GEdCDn0kmgwXSs9xXG1NemKW6OBxpvUmj1uOpVWUgEuVivXeCe6Y
    uWeI+EZEoJ+yDh1u2V7wXn5A6IoiNAUwAAAMEA3tMTh6gVShqZESIApqcte7fLUEPnYtjM
    tw4Vq/0EP3KkwL4CcoS5m9d0CI6sLlfzyWD/1EXjR8GdPZ9Rkx/NntD7EyVSIuV6MU/PVm
    +5AQXe5aZbWmD12uxAuMYOpamNzQX1zjpBXM93MOSOqjHNDVa8O0EeEqnakPqK6aa9fLOy
    cif7KZ3cJMtPrf/dUTPLMX6pUmN617CoBl5Zsw2/C8vKZqH+eneGdo8f0dmXBOJRiyo5ox
    8Co9VZWdmU5v3dAAAAG21ATWF0aXNzcy1NYWNCb29rLVByby5sb2NhbAECAwQFBgc=
    -----END OPENSSH PRIVATE KEY-----